### ISSUE TITLE
Error creating new session

### ISSUE THREAD

**Issue by 0x326** [elisescu/tty-proxy#3]
## Setup

```bash
# As of this writing, tty-proxy is at commit 5226a19d9c806af66fd18ce1dd20cbc49196a79d
docker build . -t elisescu/tty-proxy
docker run \
  -p 3456:3456 -p 8080:8080 \
  -e URL=http://localhost:8080 \
  --cap-drop=all --rm \
  elisescu/tty-proxy

```

```bash
# As of this writing, tty-share is at commit a0140aabf34b959931a8f3891b283b25da348c73
go get github.com/elisescu/tty-share
tty-share --server localhost:3456 --useTLS=false
```

## Output

`tty-proxy` logs:

```
time="2021-02-11T21:01:46Z" level=info msg="Listening on address: http://:8080, and TCP://:3456"
time="2021-02-11T21:02:24Z" level=info msg="New tty-share session 8KLzak2oWHF4ayPWXO26s25lnE5r_8vzneYdZtm8lwztwrdYRkT_FDMb6E6KBhr22i4 from for 172.17.0.1:45816"
time="2021-02-11T21:02:24Z" level=info msg="tty-share session 8KLzak2oWHF4ayPWXO26s25lnE5r_8vzneYdZtm8lwztwrdYRkT_FDMb6E6KBhr22i4 closed: EOF"
```

`tty-share` output:

```
Cannot initialise the protocol connection: Cannot decode message: unexpected end of JSON input
```

**Comment by elisescu** [comment]
It looks like you might be using an old version of tty-share, which was using the old server (tty-server, instead o tty-proxy). You can read more on that [here](https://github.com/elisescu/tty-share/blob/v2/doc/old-version.md).
At a quick look, I can't find the `a0140aabf34b959931a8f3891b283b25da348c73` commit  you mention in the history - are you sure you're running the right/latest version of tty-share (which is the one supposed to work with tty-proxy)?

**Comment by 0x326** [comment]
The `master` branch of `tty-share` currently points to https://github.com/elisescu/tty-share/commit/a0140aabf34b959931a8f3891b283b25da348c73.  Upon further research, this seems to be the version that works with `tty-server`, not `tty-proxy`

**Comment by 0x326** [comment]
I installed `tty-share` just yesterday using:
```bash
go get github.com/elisescu/tty-share
```

**Comment by elisescu** [comment]
My bad with the commit hash - you're right, it's part of the master (I was behind locally).

But the binary you run doesn't seem to be built from that commit. The `--server` and `--useTLS=false` have been replaced by `--tty-proxy` and `--no-tls` ([main.go:76](https://github.com/elisescu/tty-share/blob/a0140aabf34b959931a8f3891b283b25da348c73/main.go#L76)) respectively. 
Maybe try a `which tty-share` and see if it's the one you expect to have been installed by `go get`?

**Comment by 0x326** [comment]
I found something interesting.  Looking at my shell history, if I re-run the following:
```bash
export GO111MODULE=on
go get github.com/elisescu/tty-share
```
then I get the old version of `tty-share` that requires `tty-server`.  

If I run:
```bash
unset GO111MODULE
go get github.com/elisescu/tty-share
```
then I get the new version that uses `tty-proxy`

**Comment by 0x326** [comment]
However, in either case `tty-share --version` prints `0.0.0`

**Comment by elisescu** [comment]
Huh, I didn't expect that. I have no idea why it would get a different version whether you set that env, but it sounds super weird. I'll try to find out more.
The version string is expected to be 0.0.0 since it's built via the `go get` command, which has no support for doing something like what I do when I release it via the [release script](https://github.com/elisescu/tty-share/blob/master/scripts/release.sh#L2).

**Comment by elisescu** [comment]
@0x326 I'll close this issue. Not sure if you managed to solve, but if you need any other input from my side, feel free to open it again.
