### ISSUE TITLE
nginx proxy_log_format

### ISSUE THREAD

**Issue by pmav99** [elisescu/tty-proxy#4]
In the nginx snippet the `proxy_log_format` is used. Would you mind  sharing that one too?

Thanks for your great work :)

**Comment by elisescu** [comment]
Sure, here it is:
```
log_format proxy_log_format '[$time_local] $remote_addr - $remote_user - $server_name  to: $upstream_addr: $request upstream_response_time $upstream_response_time msec $msec request_time $request_time';
```

I will also add it to the nginx snippet in the repo :)
